name: ropulva_task
description: "interview task"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  intl: ^0.17.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  dartz: ^0.10.1
  window_manager: ^0.3.8
  internet_connection_checker_plus: ^2.2.0
  shimmer: ^3.0.0
  path_provider: ^2.1.2
  flutter_native_splash: ^2.3.9
  lottie: ^3.1.0
  device_info_plus: ^9.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  color_dark: "#FFFFFF"
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/lotties/
    - assets/images/

